const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('updater', {
  getState: () => ipcRenderer.invoke('updater:getState'),
  check: () => ipcRenderer.send('updater:check'),
  downloadUpdate: () => ipcRenderer.send('updater:download'),
  quitAndInstall: () => ipcRenderer.send('updater:install'),
  onState: (cb) => ipcRenderer.on('updater:state', (_e, state) => cb(state)),
  onProgress: (cb) => ipcRenderer.on('updater:progress', (_e, progress) => cb(progress)),
  onDownloaded: (cb) => ipcRenderer.on('updater:downloaded', () => cb()),
  onError: (cb) => ipcRenderer.on('updater:error', (_e, message) => cb(message)),
});

contextBridge.exposeInMainWorld('desktop', {
  getSettings: () => ipcRenderer.invoke('desktop:getSettings'),
  chooseFolder: () => ipcRenderer.invoke('desktop:chooseFolder'),
  openFolder: () => ipcRenderer.send('desktop:openFolder'),
  saveJob: (jobId, clientId, count, folder, artist, album) => ipcRenderer.send('desktop:saveJob', { jobId, clientId, count, folder, artist, album }),
  showInFolder: (jobId) => ipcRenderer.send('desktop:showInFolder', jobId),
  openSaved: (jobId) => ipcRenderer.send('desktop:openSaved', jobId),
  savedExists: (ids) => ipcRenderer.invoke('desktop:savedExists', ids),
  setOptions: (patch) => ipcRenderer.send('desktop:setOptions', patch),
  retryComponents: () => ipcRenderer.send('components:retry'),
  onPasteUrl: (cb) => ipcRenderer.on('desktop:pasteUrl', (_e, info) => cb(info)),
  setProgress: (value) => ipcRenderer.send('desktop:setProgress', value),
  windowControl: (action) => ipcRenderer.send('window:control', action),
  setTheme: (theme) => ipcRenderer.send('appearance:theme', theme),
  setUi: (ui) => ipcRenderer.send('appearance:ui', ui),
  openDataFolder: () => ipcRenderer.send('desktop:openDataFolder'),
  onWindowState: (cb) => ipcRenderer.on('window:state', (_e, state) => cb(state)),
  onSaved: (cb) => ipcRenderer.on('desktop:saved', (_e, info) => cb(info)),
  getEngine: () => ipcRenderer.invoke('engine:getState'),
  updateEngine: () => ipcRenderer.send('engine:update'),
  onEngine: (cb) => ipcRenderer.on('engine:state', (_e, state) => cb(state)),
  showLibraryFile: (rel) => ipcRenderer.send('desktop:showLibraryFile', rel),
  installExtension: () => ipcRenderer.invoke('desktop:installExtension'),
  exportBackup: (text) => ipcRenderer.invoke('desktop:exportBackup', text),
  importBackup: () => ipcRenderer.invoke('desktop:importBackup'),
  setDownloadDir: (dir) => ipcRenderer.invoke('desktop:setDownloadDir', dir),
});
